
const RECIPES = [
  {
    id: 1,
    title: "White Chicken Lasagna",
    subtitle: "No pasta sheets — rich & creamy",
    category: "Chicken",
    time: 55,
    servings: 6,
    difficulty: "Medium",
    emoji: "🍗",
    color: "#e8d5b7",
    ingredients: [
      { item: "Chicken breasts, cooked & shredded", amount: 3, unit: "cups" },
      { item: "Cream cheese, softened", amount: 8, unit: "oz" },
      { item: "Ricotta cheese", amount: 1.5, unit: "cups" },
      { item: "Mozzarella cheese, shredded", amount: 2, unit: "cups" },
      { item: "Parmesan cheese, grated", amount: 0.5, unit: "cup" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Baby spinach", amount: 2, unit: "cups" },
      { item: "Chicken broth", amount: 1, unit: "cup" },
      { item: "Heavy cream", amount: 1, unit: "cup" },
      { item: "Italian seasoning", amount: 2, unit: "tsp" },
      { item: "Salt & black pepper", amount: 1, unit: "to taste" },
      { item: "Butter", amount: 2, unit: "tbsp" }
    ],
    steps: [
      "Preheat oven to 375°F (190°C). Grease a 9×13-inch baking dish.",
      "In a large skillet over medium heat, melt butter and sauté garlic until fragrant, about 1 minute.",
      "Add chicken broth and heavy cream, bring to a gentle simmer. Stir in cream cheese until fully melted and smooth.",
      "Mix in ricotta, half the mozzarella, and Italian seasoning. Season well with salt and pepper.",
      "Fold in the shredded chicken and baby spinach until evenly combined.",
      "Pour the mixture into the prepared baking dish and spread evenly.",
      "Top generously with remaining mozzarella and all the Parmesan.",
      "Bake uncovered for 30–35 minutes until bubbly and golden on top.",
      "Let rest 10 minutes before serving. Garnish with fresh parsley if desired."
    ]
  },
  {
    id: 2,
    title: "Chicken Alfredo",
    subtitle: "Silky, restaurant-style",
    category: "Chicken",
    time: 35,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍝",
    color: "#f5e6c8",
    ingredients: [
      { item: "Fettuccine pasta", amount: 12, unit: "oz" },
      { item: "Chicken breasts", amount: 2, unit: "large" },
      { item: "Heavy cream", amount: 2, unit: "cups" },
      { item: "Butter", amount: 4, unit: "tbsp" },
      { item: "Parmesan cheese, freshly grated", amount: 1.5, unit: "cups" },
      { item: "Garlic cloves, minced", amount: 3, unit: "cloves" },
      { item: "Olive oil", amount: 2, unit: "tbsp" },
      { item: "Italian seasoning", amount: 1, unit: "tsp" },
      { item: "Salt & black pepper", amount: 1, unit: "to taste" },
      { item: "Fresh parsley, chopped", amount: 2, unit: "tbsp" }
    ],
    steps: [
      "Cook fettuccine according to package instructions. Reserve 1 cup of pasta water before draining.",
      "Season chicken breasts generously with Italian seasoning, salt, and pepper.",
      "Heat olive oil in a large skillet over medium-high heat. Cook chicken 6–7 minutes per side until golden and cooked through. Let rest, then slice.",
      "In the same skillet, melt butter over medium heat. Sauté garlic for 1 minute until fragrant.",
      "Pour in heavy cream and bring to a gentle simmer. Cook 3–4 minutes, stirring occasionally.",
      "Remove pan from heat and stir in Parmesan until the sauce is smooth and silky. Add pasta water if needed.",
      "Toss in cooked fettuccine, coating every strand. Taste and adjust seasoning.",
      "Serve topped with sliced chicken and fresh parsley."
    ]
  },
  {
    id: 3,
    title: "Crispy Salmon",
    subtitle: "The easiest ever — pan-seared perfection",
    category: "Seafood",
    time: 20,
    servings: 2,
    difficulty: "Easy",
    emoji: "🐟",
    color: "#ffd5b5",
    ingredients: [
      { item: "Salmon fillets, skin-on", amount: 2, unit: "fillets" },
      { item: "Olive oil", amount: 2, unit: "tbsp" },
      { item: "Garlic powder", amount: 1, unit: "tsp" },
      { item: "Smoked paprika", amount: 0.5, unit: "tsp" },
      { item: "Dried dill", amount: 0.5, unit: "tsp" },
      { item: "Lemon", amount: 1, unit: "whole" },
      { item: "Salt & black pepper", amount: 1, unit: "to taste" },
      { item: "Butter", amount: 1, unit: "tbsp" }
    ],
    steps: [
      "Pat salmon fillets completely dry with paper towels — this is key to crispy skin.",
      "Mix garlic powder, smoked paprika, dill, salt, and pepper. Season fillets on both sides.",
      "Heat a cast-iron or heavy skillet over high heat until very hot. Add olive oil.",
      "Place salmon skin-side DOWN. Press gently with a spatula for 10 seconds to prevent curling.",
      "Cook undisturbed for 4–5 minutes until the skin is deeply golden and crispy.",
      "Flip, add butter, and cook 1–2 more minutes, basting with the butter.",
      "Squeeze fresh lemon juice over the top and serve immediately."
    ]
  },
  {
    id: 4,
    title: "Roasted Whole Chicken",
    subtitle: "With potatoes & carrots",
    category: "Chicken",
    time: 90,
    servings: 6,
    difficulty: "Medium",
    emoji: "🍗",
    color: "#e6c9a0",
    ingredients: [
      { item: "Whole chicken", amount: 1, unit: "(4–5 lb)" },
      { item: "Baby potatoes, halved", amount: 1.5, unit: "lbs" },
      { item: "Carrots, cut in chunks", amount: 4, unit: "large" },
      { item: "Olive oil", amount: 4, unit: "tbsp" },
      { item: "Garlic cloves, minced", amount: 6, unit: "cloves" },
      { item: "Rosemary, fresh", amount: 3, unit: "sprigs" },
      { item: "Thyme, fresh", amount: 3, unit: "sprigs" },
      { item: "Lemon", amount: 1, unit: "whole" },
      { item: "Butter, softened", amount: 3, unit: "tbsp" },
      { item: "Paprika", amount: 1, unit: "tsp" },
      { item: "Salt & pepper", amount: 1, unit: "generously" }
    ],
    steps: [
      "Preheat oven to 425°F (220°C). Pat chicken dry inside and out.",
      "Mix butter with half the garlic, paprika, salt, and pepper. Rub under skin and all over the outside.",
      "Stuff the cavity with lemon halves (squeezed), rosemary, and thyme.",
      "Toss potatoes and carrots with olive oil, remaining garlic, salt, and pepper.",
      "Scatter vegetables in a large roasting pan. Place chicken on top, breast side up.",
      "Roast for 1 hour to 1 hour 20 minutes, until internal temp reads 165°F and juices run clear.",
      "Baste every 30 minutes with pan juices for extra golden skin.",
      "Rest 15 minutes before carving. Serve with the pan-roasted vegetables."
    ]
  },
  {
    id: 5,
    title: "Chicken & Broccoli Rice Bowl",
    subtitle: "Quick, balanced & satisfying",
    category: "Chicken",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    emoji: "🥦",
    color: "#d4e8d0",
    ingredients: [
      { item: "Chicken thighs, boneless skinless", amount: 1.5, unit: "lbs" },
      { item: "Broccoli florets", amount: 3, unit: "cups" },
      { item: "Jasmine rice, cooked", amount: 2, unit: "cups" },
      { item: "Soy sauce", amount: 3, unit: "tbsp" },
      { item: "Sesame oil", amount: 1, unit: "tbsp" },
      { item: "Garlic cloves, minced", amount: 3, unit: "cloves" },
      { item: "Fresh ginger, grated", amount: 1, unit: "tsp" },
      { item: "Honey", amount: 1, unit: "tbsp" },
      { item: "Cornstarch", amount: 1, unit: "tsp" },
      { item: "Sesame seeds", amount: 1, unit: "tbsp" },
      { item: "Green onions", amount: 3, unit: "stalks" }
    ],
    steps: [
      "Cut chicken into bite-sized pieces. Mix soy sauce, sesame oil, honey, ginger, and cornstarch in a bowl.",
      "Add chicken to the marinade and toss to coat. Let sit 10 minutes.",
      "Steam or blanch broccoli florets until bright green and just tender, 3–4 minutes.",
      "Heat a wok or large skillet over high heat with a little oil. Add garlic and stir-fry 30 seconds.",
      "Add chicken with marinade. Cook 5–6 minutes, stirring frequently, until caramelized and cooked through.",
      "Add broccoli and toss everything together for 1 minute.",
      "Serve over warm jasmine rice, garnished with sesame seeds and sliced green onions."
    ]
  },
  {
    id: 6,
    title: "Homemade Smash Burgers",
    subtitle: "With crispy seasoned fries",
    category: "Beef",
    time: 35,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍔",
    color: "#e8c9a0",
    ingredients: [
      { item: "80/20 ground beef", amount: 1.5, unit: "lbs" },
      { item: "American cheese slices", amount: 8, unit: "slices" },
      { item: "Brioche buns", amount: 4, unit: "buns" },
      { item: "Russet potatoes", amount: 4, unit: "large" },
      { item: "Garlic powder", amount: 1, unit: "tsp" },
      { item: "Smoked paprika", amount: 1, unit: "tsp" },
      { item: "Mayonnaise", amount: 3, unit: "tbsp" },
      { item: "Ketchup", amount: 2, unit: "tbsp" },
      { item: "Pickle slices", amount: 1, unit: "handful" },
      { item: "Shredded lettuce", amount: 1, unit: "cup" },
      { item: "Vegetable oil", amount: 2, unit: "tbsp" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "For fries: cut potatoes into thin strips, soak in cold water 30 minutes, drain and dry thoroughly.",
      "Toss fries with oil, garlic powder, paprika, salt. Air fry at 400°F for 18–20 min, or bake at 425°F for 35 min, flipping halfway.",
      "Divide beef into 3-oz balls — do NOT overwork. Season with salt and pepper.",
      "Heat a cast-iron skillet or griddle over screaming high heat until smoking.",
      "Place beef balls on the skillet and immediately smash flat with a spatula (or burger press). Press hard!",
      "Cook 2–3 minutes until edges are deeply caramelized. Lay cheese on top, cover with a dome lid for 30 seconds.",
      "Stack: toasted bun → burger → second cheese-laden patty → pickles → lettuce → special sauce (mix mayo & ketchup).",
      "Serve immediately with the hot crispy fries."
    ]
  },
  {
    id: 7,
    title: "Ground Beef Philly Cheesesteaks",
    subtitle: "Quick weeknight version",
    category: "Beef",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    emoji: "🥖",
    color: "#f0d5b0",
    ingredients: [
      { item: "Ground beef (80/20)", amount: 1.5, unit: "lbs" },
      { item: "Hoagie rolls", amount: 4, unit: "rolls" },
      { item: "Provolone cheese", amount: 8, unit: "slices" },
      { item: "Green bell pepper, sliced", amount: 1, unit: "large" },
      { item: "Yellow onion, sliced", amount: 1, unit: "large" },
      { item: "Mushrooms, sliced", amount: 1, unit: "cup" },
      { item: "Worcestershire sauce", amount: 2, unit: "tbsp" },
      { item: "Garlic powder", amount: 1, unit: "tsp" },
      { item: "Butter", amount: 2, unit: "tbsp" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Melt butter in a large skillet over medium-high heat. Add onions and peppers, sauté until soft and caramelized, about 8 minutes.",
      "Add mushrooms and cook 3 more minutes. Remove vegetables to a bowl.",
      "Add ground beef to the same skillet. Break up and cook until browned. Drain excess fat.",
      "Season beef with Worcestershire, garlic powder, salt, and pepper. Stir well.",
      "Return vegetables to the pan and mix everything together.",
      "Toast hoagie rolls cut-side down in a dry skillet until golden.",
      "Pile beef mixture onto rolls, top with provolone slices, and either broil or cover with lid to melt the cheese.",
      "Serve hot and enjoy!"
    ]
  },
  {
    id: 8,
    title: "Fancy Hamburger Helper",
    subtitle: "Elevated comfort food",
    category: "Beef",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍲",
    color: "#f0c8a8",
    ingredients: [
      { item: "Ground beef", amount: 1, unit: "lb" },
      { item: "Elbow macaroni, uncooked", amount: 2, unit: "cups" },
      { item: "Beef broth", amount: 2, unit: "cups" },
      { item: "Heavy cream", amount: 1, unit: "cup" },
      { item: "Sharp cheddar, shredded", amount: 2, unit: "cups" },
      { item: "Diced tomatoes (canned)", amount: 1, unit: "14-oz can" },
      { item: "Garlic cloves, minced", amount: 3, unit: "cloves" },
      { item: "Onion, diced", amount: 1, unit: "medium" },
      { item: "Smoked paprika", amount: 1, unit: "tsp" },
      { item: "Chili powder", amount: 0.5, unit: "tsp" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Brown ground beef in a large deep skillet over medium-high heat. Drain fat.",
      "Add onion and garlic to the beef, cook 3 minutes until softened.",
      "Stir in smoked paprika and chili powder; cook 1 minute.",
      "Add uncooked macaroni, beef broth, cream, and diced tomatoes. Stir to combine.",
      "Bring to a boil, then reduce heat, cover, and simmer 12–14 minutes until pasta is tender, stirring occasionally.",
      "Remove from heat. Stir in shredded cheddar in handfuls until melted and creamy.",
      "Season to taste. Garnish with fresh chives or parsley and extra cheese."
    ]
  },
  {
    id: 9,
    title: "Homemade Meatball Subs",
    subtitle: "Saucy, cheesy & loaded",
    category: "Beef",
    time: 45,
    servings: 4,
    difficulty: "Medium",
    emoji: "🥖",
    color: "#e8b8a0",
    ingredients: [
      { item: "Ground beef", amount: 1, unit: "lb" },
      { item: "Ground pork", amount: 0.5, unit: "lb" },
      { item: "Parmesan, grated", amount: 0.5, unit: "cup" },
      { item: "Breadcrumbs", amount: 0.5, unit: "cup" },
      { item: "Egg", amount: 1, unit: "large" },
      { item: "Garlic cloves, minced", amount: 3, unit: "cloves" },
      { item: "Italian seasoning", amount: 1, unit: "tbsp" },
      { item: "Marinara sauce", amount: 2, unit: "cups" },
      { item: "Hoagie rolls", amount: 4, unit: "rolls" },
      { item: "Mozzarella, shredded", amount: 1.5, unit: "cups" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Preheat oven to 400°F. Combine beef, pork, breadcrumbs, Parmesan, egg, garlic, Italian seasoning, salt, and pepper.",
      "Mix gently with hands until just combined — don't overwork. Roll into 1.5-inch balls.",
      "Place on a baking sheet and bake 18–20 minutes until browned and cooked through.",
      "Warm marinara in a saucepan. Add meatballs and simmer 5 minutes.",
      "Toast rolls cut-side up under the broiler for 2 minutes.",
      "Load meatballs with sauce onto each roll. Top with mozzarella.",
      "Broil assembled subs for 2–3 minutes until cheese is bubbly and golden. Serve immediately."
    ]
  },
  {
    id: 10,
    title: "Spiced Chicken with Rice & Potatoes",
    subtitle: "One-pan weeknight win",
    category: "Chicken",
    time: 50,
    servings: 4,
    difficulty: "Medium",
    emoji: "🍛",
    color: "#e8d0a8",
    ingredients: [
      { item: "Chicken thighs, bone-in skin-on", amount: 4, unit: "pieces" },
      { item: "Jasmine rice", amount: 1.5, unit: "cups" },
      { item: "Baby potatoes, halved", amount: 1, unit: "lb" },
      { item: "Chicken broth", amount: 2.5, unit: "cups" },
      { item: "Olive oil", amount: 3, unit: "tbsp" },
      { item: "Cumin", amount: 1, unit: "tsp" },
      { item: "Turmeric", amount: 0.5, unit: "tsp" },
      { item: "Smoked paprika", amount: 1, unit: "tsp" },
      { item: "Cinnamon", amount: 0.25, unit: "tsp" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Lemon juice", amount: 2, unit: "tbsp" },
      { item: "Fresh cilantro", amount: 1, unit: "handful" }
    ],
    steps: [
      "Mix cumin, turmeric, paprika, cinnamon, garlic, lemon juice, olive oil, salt, and pepper. Coat chicken and potatoes in this spice mixture.",
      "Sear chicken skin-side down in a large oven-safe pan over medium-high heat, 5 minutes until golden. Flip and cook 2 more minutes. Set aside.",
      "In the same pan, toast rice 1–2 minutes. Add broth and bring to a simmer.",
      "Nestle chicken and potatoes into the rice. Cover tightly with foil.",
      "Bake at 375°F for 30–35 minutes until rice is cooked and chicken is tender.",
      "Let rest 5 minutes. Fluff rice and garnish with fresh cilantro."
    ]
  },
  {
    id: 11,
    title: "Crispy Chicken",
    subtitle: "With sautéed brussels sprouts & creamy sauce",
    category: "Chicken",
    time: 40,
    servings: 4,
    difficulty: "Medium",
    emoji: "🍗",
    color: "#e8c8a0",
    ingredients: [
      { item: "Chicken breasts", amount: 4, unit: "large" },
      { item: "Brussels sprouts, halved", amount: 1, unit: "lb" },
      { item: "Panko breadcrumbs", amount: 1, unit: "cup" },
      { item: "Parmesan, grated", amount: 0.5, unit: "cup" },
      { item: "Egg", amount: 2, unit: "large" },
      { item: "Heavy cream", amount: 0.5, unit: "cup" },
      { item: "Dijon mustard", amount: 1, unit: "tbsp" },
      { item: "Garlic cloves, minced", amount: 2, unit: "cloves" },
      { item: "Olive oil", amount: 3, unit: "tbsp" },
      { item: "Lemon", amount: 1, unit: "whole" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Pound chicken breasts to even thickness. Season with salt and pepper.",
      "Mix panko and Parmesan in a shallow dish. Dip chicken in egg wash, then coat in breadcrumb mixture.",
      "Pan-fry in hot oil 4–5 minutes per side until golden and cooked through. Transfer to oven at 400°F for 5–10 min if needed.",
      "In the same pan, sauté brussels sprouts cut-side down in oil over high heat until caramelized, 6–7 minutes.",
      "Make sauce: combine cream, Dijon, garlic, and lemon juice in a small pan. Simmer until slightly thickened.",
      "Serve crispy chicken over brussels sprouts with sauce drizzled generously."
    ]
  },
  {
    id: 12,
    title: "Loaded Sweet Potato Pizza",
    subtitle: "Sweet potato base, all the toppings",
    category: "Sweet Potato",
    time: 40,
    servings: 2,
    difficulty: "Easy",
    emoji: "🍕",
    color: "#f0b870",
    ingredients: [
      { item: "Large sweet potatoes", amount: 2, unit: "large" },
      { item: "Marinara sauce", amount: 0.5, unit: "cup" },
      { item: "Mozzarella, shredded", amount: 1, unit: "cup" },
      { item: "Pepperoni slices", amount: 20, unit: "slices" },
      { item: "Bell pepper, diced", amount: 0.5, unit: "medium" },
      { item: "Red onion, thinly sliced", amount: 0.25, unit: "medium" },
      { item: "Italian seasoning", amount: 1, unit: "tsp" },
      { item: "Olive oil", amount: 1, unit: "tbsp" },
      { item: "Red pepper flakes", amount: 1, unit: "pinch" }
    ],
    steps: [
      "Preheat oven to 400°F. Slice sweet potatoes lengthwise into 1/2-inch planks.",
      "Brush both sides with olive oil, season with salt. Roast on a baking sheet 20 minutes, flipping halfway.",
      "Remove from oven. Spread marinara on each plank like a pizza base.",
      "Top with mozzarella, pepperoni, bell pepper, and red onion.",
      "Sprinkle Italian seasoning and red pepper flakes.",
      "Bake 10 more minutes until cheese is melted and bubbly.",
      "Let cool slightly before serving. The sweet potato base is deliciously crispy on the bottom."
    ]
  },
  {
    id: 13,
    title: "Sweet Potato Parmesan",
    subtitle: "Pasta-style comfort dish",
    category: "Sweet Potato",
    time: 35,
    servings: 3,
    difficulty: "Easy",
    emoji: "🍠",
    color: "#f0c080",
    ingredients: [
      { item: "Sweet potatoes, large", amount: 2, unit: "large" },
      { item: "Marinara sauce", amount: 1.5, unit: "cups" },
      { item: "Mozzarella, shredded", amount: 1.5, unit: "cups" },
      { item: "Parmesan, grated", amount: 0.5, unit: "cup" },
      { item: "Egg", amount: 1, unit: "large" },
      { item: "Panko breadcrumbs", amount: 0.5, unit: "cup" },
      { item: "Italian seasoning", amount: 1, unit: "tsp" },
      { item: "Olive oil", amount: 2, unit: "tbsp" },
      { item: "Fresh basil", amount: 1, unit: "handful" }
    ],
    steps: [
      "Preheat oven to 400°F. Slice sweet potato into 1/2-inch rounds.",
      "Dip each round in egg, then coat in seasoned panko mixed with Italian seasoning.",
      "Pan-fry in olive oil 3 minutes per side until golden and crispy.",
      "Arrange in a baking dish. Pour marinara between and around the slices.",
      "Top each slice with mozzarella and a sprinkle of Parmesan.",
      "Bake 15 minutes until cheese is melted and sauce is bubbling.",
      "Garnish with fresh basil and serve as a main or side dish."
    ]
  },
  {
    id: 14,
    title: "Mini Sweet Potato Taco Melts",
    subtitle: "Crispy, cheesy little bites",
    category: "Sweet Potato",
    time: 30,
    servings: 3,
    difficulty: "Easy",
    emoji: "🌮",
    color: "#f5c878",
    ingredients: [
      { item: "Sweet potatoes", amount: 2, unit: "medium" },
      { item: "Seasoned ground beef or turkey", amount: 0.75, unit: "lb" },
      { item: "Taco seasoning", amount: 1, unit: "packet" },
      { item: "Cheddar cheese, shredded", amount: 1, unit: "cup" },
      { item: "Sour cream", amount: 3, unit: "tbsp" },
      { item: "Salsa", amount: 0.25, unit: "cup" },
      { item: "Fresh jalapeño, sliced", amount: 1, unit: "jalapeño" },
      { item: "Lime juice", amount: 1, unit: "tbsp" },
      { item: "Fresh cilantro", amount: 1, unit: "handful" }
    ],
    steps: [
      "Slice sweet potatoes into 1/4-inch rounds. Roast at 400°F for 20 minutes until just tender.",
      "Brown ground meat in a skillet. Add taco seasoning and a splash of water. Simmer 2 minutes.",
      "Top each sweet potato round with a spoonful of taco meat.",
      "Add a pinch of cheddar on top of each.",
      "Broil for 3–4 minutes until cheese is melted and bubbly.",
      "Finish with a small dollop of sour cream, a spoonful of salsa, jalapeño slice, and cilantro. Squeeze lime over the top."
    ]
  },
  {
    id: 15,
    title: "Loaded Sweet Potato",
    subtitle: "Ground beef, cheese & jalapeños",
    category: "Sweet Potato",
    time: 60,
    servings: 2,
    difficulty: "Easy",
    emoji: "🍠",
    color: "#e8b060",
    ingredients: [
      { item: "Large sweet potatoes", amount: 2, unit: "large" },
      { item: "Ground beef", amount: 0.75, unit: "lb" },
      { item: "Cheddar cheese, shredded", amount: 1, unit: "cup" },
      { item: "Jalapeños, sliced", amount: 2, unit: "jalapeños" },
      { item: "Sour cream", amount: 3, unit: "tbsp" },
      { item: "Green onions", amount: 3, unit: "stalks" },
      { item: "Garlic powder", amount: 0.5, unit: "tsp" },
      { item: "Cumin", amount: 0.5, unit: "tsp" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Preheat oven to 400°F. Poke sweet potatoes all over with a fork.",
      "Rub with olive oil and salt. Bake directly on oven rack for 45–50 minutes until completely soft.",
      "Cook ground beef with garlic powder, cumin, salt, and pepper until browned. Drain fat.",
      "Split baked sweet potatoes open. Fluff the insides with a fork.",
      "Load with seasoned beef, then pile on cheddar cheese.",
      "Return to oven for 5 minutes to melt the cheese.",
      "Top with jalapeños, sour cream, and sliced green onions. Serve hot."
    ]
  },
  {
    id: 16,
    title: "Sourdough Pizza Toast",
    subtitle: "Thick, crispy & fully loaded",
    category: "Pizza & Flatbreads",
    time: 20,
    servings: 2,
    difficulty: "Easy",
    emoji: "🍕",
    color: "#e8c8a0",
    ingredients: [
      { item: "Thick sourdough slices", amount: 4, unit: "slices" },
      { item: "Pizza sauce", amount: 0.5, unit: "cup" },
      { item: "Mozzarella, shredded", amount: 1.5, unit: "cups" },
      { item: "Pepperoni", amount: 20, unit: "slices" },
      { item: "Italian seasoning", amount: 1, unit: "tsp" },
      { item: "Garlic butter", amount: 2, unit: "tbsp" },
      { item: "Red pepper flakes", amount: 1, unit: "pinch" }
    ],
    steps: [
      "Preheat broiler to high. Place sourdough slices on a baking sheet.",
      "Brush each slice with garlic butter. Toast under broiler 2 minutes until lightly golden.",
      "Spread pizza sauce on each slice, all the way to the edges.",
      "Add a generous layer of mozzarella. Pile on pepperoni.",
      "Sprinkle Italian seasoning and red pepper flakes.",
      "Broil 3–4 minutes until cheese is bubbly, golden, and slightly charred at the edges.",
      "Let cool 1 minute before cutting. The sourdough stays perfectly crispy underneath."
    ]
  },
  {
    id: 17,
    title: "Homemade Flatbread",
    subtitle: "Skillet quesadilla style",
    category: "Pizza & Flatbreads",
    time: 25,
    servings: 2,
    difficulty: "Easy",
    emoji: "🫓",
    color: "#f0d5b0",
    ingredients: [
      { item: "All-purpose flour", amount: 2, unit: "cups" },
      { item: "Greek yogurt", amount: 0.75, unit: "cup" },
      { item: "Baking powder", amount: 1, unit: "tsp" },
      { item: "Salt", amount: 0.5, unit: "tsp" },
      { item: "Mozzarella, shredded", amount: 1, unit: "cup" },
      { item: "Your choice of fillings", amount: 1, unit: "cup" },
      { item: "Butter", amount: 2, unit: "tbsp" }
    ],
    steps: [
      "Mix flour, yogurt, baking powder, and salt. Knead into a smooth dough — add a splash of water if needed.",
      "Divide dough in half. Roll each piece thin on a floured surface.",
      "Heat a dry skillet over medium-high heat. Cook flatbread 2–3 minutes per side until charred spots appear.",
      "Lower heat. Add cheese and chosen fillings to one side. Fold over and press.",
      "Melt butter in the pan, flip flatbread and cook until golden and cheese is fully melted.",
      "Slice and serve hot. Perfect with dips, salsa, or sour cream."
    ]
  },
  {
    id: 18,
    title: "Meat Lovers Skillet Pizza",
    subtitle: "Cast-iron perfection",
    category: "Pizza & Flatbreads",
    time: 35,
    servings: 3,
    difficulty: "Medium",
    emoji: "🍕",
    color: "#e8b8a0",
    ingredients: [
      { item: "Pizza dough (store-bought)", amount: 1, unit: "ball" },
      { item: "Pizza sauce", amount: 0.5, unit: "cup" },
      { item: "Mozzarella, shredded", amount: 2, unit: "cups" },
      { item: "Italian sausage, crumbled & cooked", amount: 0.5, unit: "cup" },
      { item: "Pepperoni", amount: 20, unit: "slices" },
      { item: "Cooked bacon, crumbled", amount: 4, unit: "strips" },
      { item: "Olive oil", amount: 2, unit: "tbsp" },
      { item: "Garlic powder", amount: 0.5, unit: "tsp" },
      { item: "Italian seasoning", amount: 1, unit: "tsp" }
    ],
    steps: [
      "Preheat oven to 475°F. Place a 12-inch cast-iron skillet in the oven for 10 minutes to get smoking hot.",
      "Stretch dough to roughly 12-inch circle. Let it rest a few minutes to relax.",
      "Carefully remove hot skillet. Add olive oil to the pan, swirl to coat.",
      "Lay dough in pan, pressing to the edges. It will sizzle — that's perfect.",
      "Spread sauce, then load on mozzarella, sausage, pepperoni, and bacon.",
      "Bake 12–15 minutes until crust is deep golden and cheese is bubbling.",
      "Let rest 3 minutes in pan. Slide out, slice, and serve straight from the skillet."
    ]
  },
  {
    id: 19,
    title: "One-Skillet Ground Beef & Black Bean Rice Bake",
    subtitle: "Cheesy, hearty & all in one pan",
    category: "Skillet Dinners",
    time: 35,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍳",
    color: "#d4c8a0",
    ingredients: [
      { item: "Ground beef", amount: 1, unit: "lb" },
      { item: "Black beans (canned, drained)", amount: 1, unit: "15-oz can" },
      { item: "Long-grain rice, uncooked", amount: 1, unit: "cup" },
      { item: "Beef broth", amount: 2, unit: "cups" },
      { item: "Diced tomatoes (canned)", amount: 1, unit: "14-oz can" },
      { item: "Onion, diced", amount: 1, unit: "medium" },
      { item: "Garlic cloves, minced", amount: 3, unit: "cloves" },
      { item: "Cumin", amount: 1, unit: "tsp" },
      { item: "Chili powder", amount: 1, unit: "tsp" },
      { item: "Cheddar cheese, shredded", amount: 1.5, unit: "cups" },
      { item: "Green onions", amount: 2, unit: "stalks" }
    ],
    steps: [
      "Brown ground beef in a large oven-safe skillet. Drain excess fat.",
      "Add onion and garlic, cook 3 minutes until softened.",
      "Stir in cumin and chili powder. Add rice, broth, black beans, and diced tomatoes.",
      "Bring to a boil, stir well, then cover and reduce to a simmer.",
      "Cook 18–20 minutes until rice has absorbed all liquid.",
      "Top with shredded cheddar. Cover for 2 minutes, or broil 3 minutes until bubbly.",
      "Garnish with sliced green onions and serve directly from the skillet."
    ]
  },
  {
    id: 20,
    title: "Chicken & Vegetable Skillet",
    subtitle: "Green beans, mushrooms & peppers",
    category: "Skillet Dinners",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    emoji: "🥘",
    color: "#c8d8b8",
    ingredients: [
      { item: "Chicken breasts, cubed", amount: 1.5, unit: "lbs" },
      { item: "Green beans, trimmed", amount: 2, unit: "cups" },
      { item: "Mushrooms, sliced", amount: 1.5, unit: "cups" },
      { item: "Red bell pepper, sliced", amount: 1, unit: "large" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Olive oil", amount: 3, unit: "tbsp" },
      { item: "Soy sauce", amount: 2, unit: "tbsp" },
      { item: "Chicken broth", amount: 0.5, unit: "cup" },
      { item: "Italian seasoning", amount: 1, unit: "tsp" },
      { item: "Butter", amount: 1, unit: "tbsp" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Season chicken cubes with Italian seasoning, salt, and pepper.",
      "Heat olive oil in a large skillet over high heat. Sear chicken until golden, about 5–6 minutes. Set aside.",
      "In the same skillet, add a bit more oil. Sauté mushrooms until browned.",
      "Add garlic, green beans, and bell peppers. Stir-fry 4–5 minutes.",
      "Pour in soy sauce and chicken broth. Return chicken to the pan.",
      "Simmer 3–4 minutes until sauce thickens slightly. Stir in butter.",
      "Taste, adjust seasoning, and serve over rice or with crusty bread."
    ]
  },
  {
    id: 21,
    title: "Skillet Egg & Potato Hash",
    subtitle: "With scrambled egg pour-over",
    category: "Skillet Dinners",
    time: 25,
    servings: 2,
    difficulty: "Easy",
    emoji: "🍳",
    color: "#f0d0a0",
    ingredients: [
      { item: "Russet potatoes, diced small", amount: 3, unit: "medium" },
      { item: "Eggs", amount: 4, unit: "large" },
      { item: "Bell pepper, diced", amount: 1, unit: "medium" },
      { item: "Onion, diced", amount: 0.5, unit: "medium" },
      { item: "Garlic cloves, minced", amount: 2, unit: "cloves" },
      { item: "Smoked paprika", amount: 1, unit: "tsp" },
      { item: "Cheddar cheese", amount: 0.5, unit: "cup" },
      { item: "Butter", amount: 2, unit: "tbsp" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" },
      { item: "Hot sauce (optional)", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Cook diced potatoes in boiling salted water for 5 minutes until par-cooked. Drain well.",
      "Melt butter in a cast-iron skillet over medium-high heat. Add potatoes in a single layer.",
      "Cook undisturbed 4–5 minutes until crispy on the bottom. Flip and crisp the other side.",
      "Add onion, bell pepper, and garlic. Sauté until softened, about 3 minutes.",
      "Season with paprika, salt, and pepper.",
      "Whisk eggs with a splash of milk. Pour over the hash and gently stir to scramble into the potatoes.",
      "Top with cheddar, cover for 1 minute to melt. Serve with hot sauce."
    ]
  },
  {
    id: 22,
    title: "Cheesy Quesadilla Skillet",
    subtitle: "\"Nothing in the Fridge\" special",
    category: "Skillet Dinners",
    time: 15,
    servings: 2,
    difficulty: "Easy",
    emoji: "🧀",
    color: "#f5e0a0",
    ingredients: [
      { item: "Large flour tortillas", amount: 4, unit: "tortillas" },
      { item: "Cheddar or Mexican cheese blend", amount: 1.5, unit: "cups" },
      { item: "Butter", amount: 1, unit: "tbsp" },
      { item: "Sour cream", amount: 3, unit: "tbsp" },
      { item: "Salsa", amount: 0.25, unit: "cup" },
      { item: "Whatever you have! (beans, leftovers, etc.)", amount: 0.5, unit: "cup" }
    ],
    steps: [
      "Heat a large skillet over medium heat. Melt half the butter.",
      "Lay one tortilla flat in the pan. Cover one half with cheese and any fillings you have.",
      "Fold the other half over. Press gently with a spatula.",
      "Cook 2–3 minutes until golden and crispy. Flip carefully and cook the other side.",
      "Repeat with remaining tortillas. Cut into triangles.",
      "Serve with sour cream and salsa. Honestly always a hit."
    ]
  },
  {
    id: 23,
    title: "Breakfast Tacos",
    subtitle: "Scrambled egg, cheese & herb",
    category: "Breakfast & Brunch",
    time: 15,
    servings: 2,
    difficulty: "Easy",
    emoji: "🌮",
    color: "#f5e0b8",
    ingredients: [
      { item: "Small flour or corn tortillas", amount: 6, unit: "tortillas" },
      { item: "Eggs", amount: 4, unit: "large" },
      { item: "Cheddar cheese, shredded", amount: 0.5, unit: "cup" },
      { item: "Butter", amount: 1, unit: "tbsp" },
      { item: "Chives or green onions", amount: 2, unit: "tbsp" },
      { item: "Hot sauce", amount: 1, unit: "to taste" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" },
      { item: "Fresh cilantro (optional)", amount: 1, unit: "handful" }
    ],
    steps: [
      "Warm tortillas in a dry skillet over medium heat, 30 seconds per side. Keep warm in foil.",
      "Whisk eggs with salt and pepper. Melt butter in a nonstick pan over low heat.",
      "Add eggs and cook slowly, stirring gently with a spatula every few seconds.",
      "Remove from heat while still slightly underdone — residual heat finishes them.",
      "Stir in cheese off the heat so it melts gently.",
      "Fill tortillas with creamy scrambled eggs. Top with chives, cilantro, and hot sauce."
    ]
  },
  {
    id: 24,
    title: "Mixed Berry French Toast Bake",
    subtitle: "Breakfast or dessert — both work",
    category: "Breakfast & Brunch",
    time: 55,
    servings: 6,
    difficulty: "Easy",
    emoji: "🫐",
    color: "#c8b8e8",
    ingredients: [
      { item: "Brioche or challah bread, cubed", amount: 1, unit: "loaf" },
      { item: "Eggs", amount: 4, unit: "large" },
      { item: "Whole milk", amount: 1.5, unit: "cups" },
      { item: "Heavy cream", amount: 0.5, unit: "cup" },
      { item: "Vanilla extract", amount: 2, unit: "tsp" },
      { item: "Maple syrup", amount: 3, unit: "tbsp" },
      { item: "Cinnamon", amount: 1, unit: "tsp" },
      { item: "Mixed berries (fresh or frozen)", amount: 2, unit: "cups" },
      { item: "Brown sugar", amount: 2, unit: "tbsp" },
      { item: "Powdered sugar (for serving)", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Grease a 9×13 baking dish. Layer bread cubes in the dish.",
      "Whisk together eggs, milk, cream, vanilla, maple syrup, and cinnamon.",
      "Pour custard mixture over bread. Press down so every piece soaks it up.",
      "Scatter mixed berries over the top. Sprinkle with brown sugar.",
      "Cover and refrigerate overnight — or at least 1 hour.",
      "Preheat oven to 350°F. Bake uncovered 40–45 minutes until puffed and golden.",
      "Dust with powdered sugar and serve with extra maple syrup."
    ]
  },
  {
    id: 25,
    title: "Brown Sugar Espresso Iced Coffee",
    subtitle: "Café-style at home",
    category: "Drinks & Coffee",
    time: 5,
    servings: 1,
    difficulty: "Easy",
    emoji: "☕",
    color: "#c8a070",
    ingredients: [
      { item: "Espresso shots", amount: 2, unit: "shots" },
      { item: "Brown sugar", amount: 1, unit: "tbsp" },
      { item: "Cinnamon", amount: 0.25, unit: "tsp" },
      { item: "Oat milk or whole milk", amount: 0.75, unit: "cup" },
      { item: "Ice", amount: 1, unit: "cup" },
      { item: "Vanilla extract", amount: 0.25, unit: "tsp" }
    ],
    steps: [
      "Brew 2 shots of espresso. While hot, stir in brown sugar, cinnamon, and vanilla until dissolved.",
      "Let espresso cool slightly, or pour over ice immediately for maximum chill.",
      "Fill a tall glass with ice. Pour milk over the ice.",
      "Pour the sweet espresso mixture over the milk — don't stir for a beautiful layered look.",
      "Stir before drinking and enjoy. Add more brown sugar to taste."
    ]
  },
  {
    id: 26,
    title: "Banana Milk Iced Latte",
    subtitle: "Naturally sweet & creamy",
    category: "Drinks & Coffee",
    time: 5,
    servings: 1,
    difficulty: "Easy",
    emoji: "🍌",
    color: "#f5e890",
    ingredients: [
      { item: "Ripe banana", amount: 1, unit: "medium" },
      { item: "Milk or oat milk", amount: 1, unit: "cup" },
      { item: "Espresso or strong cold brew", amount: 2, unit: "shots" },
      { item: "Maple syrup", amount: 1, unit: "tsp" },
      { item: "Ice", amount: 1, unit: "cup" },
      { item: "Cinnamon", amount: 1, unit: "pinch" }
    ],
    steps: [
      "Blend banana and milk until completely smooth — this is your 'banana milk'.",
      "Pour banana milk over a glass full of ice.",
      "Add maple syrup to espresso and stir.",
      "Pour espresso over the banana milk for a layered effect.",
      "Dust with a pinch of cinnamon on top. Stir and sip."
    ]
  },
  {
    id: 27,
    title: "One-Pan Honey Garlic Chicken Thighs",
    subtitle: "Sticky, sweet & irresistible",
    category: "Chicken",
    time: 35,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍯",
    color: "#f0d080",
    ingredients: [
      { item: "Chicken thighs, bone-in skin-on", amount: 6, unit: "pieces" },
      { item: "Honey", amount: 3, unit: "tbsp" },
      { item: "Soy sauce", amount: 3, unit: "tbsp" },
      { item: "Garlic cloves, minced", amount: 5, unit: "cloves" },
      { item: "Apple cider vinegar", amount: 1, unit: "tbsp" },
      { item: "Butter", amount: 2, unit: "tbsp" },
      { item: "Fresh thyme", amount: 4, unit: "sprigs" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Season chicken thighs generously with salt and pepper.",
      "Melt butter in a large oven-safe skillet over medium-high heat. Sear chicken skin-side down 5–6 minutes until deeply golden. Flip and sear 3 more minutes.",
      "Mix honey, soy sauce, garlic, and apple cider vinegar together.",
      "Pour sauce over chicken. Add thyme sprigs. Bring to a simmer.",
      "Transfer skillet to oven at 400°F. Roast 20–25 minutes, basting every 10 minutes.",
      "Chicken is done when internal temperature reaches 165°F. Serve with pan sauce spooned over."
    ]
  },
  {
    id: 28,
    title: "Creamy Tuscan Chicken Pasta",
    subtitle: "Sun-dried tomatoes & spinach in cream sauce",
    category: "Chicken",
    time: 35,
    servings: 4,
    difficulty: "Medium",
    emoji: "🍝",
    color: "#f0c0a0",
    ingredients: [
      { item: "Penne or rigatoni pasta", amount: 12, unit: "oz" },
      { item: "Chicken breasts, sliced thin", amount: 1.5, unit: "lbs" },
      { item: "Heavy cream", amount: 1.5, unit: "cups" },
      { item: "Sun-dried tomatoes, chopped", amount: 0.5, unit: "cup" },
      { item: "Baby spinach", amount: 3, unit: "cups" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Parmesan, grated", amount: 0.75, unit: "cup" },
      { item: "Italian seasoning", amount: 1.5, unit: "tsp" },
      { item: "Chicken broth", amount: 0.5, unit: "cup" },
      { item: "Olive oil", amount: 2, unit: "tbsp" }
    ],
    steps: [
      "Cook pasta to al dente. Reserve 1/2 cup pasta water. Drain and set aside.",
      "Season chicken with Italian seasoning, salt, and pepper. Sear in olive oil 4–5 minutes per side. Slice and set aside.",
      "In the same pan, sauté garlic and sun-dried tomatoes 1 minute.",
      "Pour in chicken broth and cream. Simmer 3–4 minutes.",
      "Stir in Parmesan until melted. Add spinach and let it wilt.",
      "Toss pasta and chicken into the sauce, adding pasta water if needed to loosen.",
      "Taste and adjust seasoning. Serve with extra Parmesan."
    ]
  },
  {
    id: 29,
    title: "Buffalo Chicken Casserole",
    subtitle: "Spicy, cheesy & crowd-pleasing",
    category: "Chicken",
    time: 45,
    servings: 6,
    difficulty: "Easy",
    emoji: "🌶️",
    color: "#f0a878",
    ingredients: [
      { item: "Chicken, cooked & shredded", amount: 3, unit: "cups" },
      { item: "Pasta (rotini or penne)", amount: 2, unit: "cups" },
      { item: "Buffalo sauce", amount: 0.75, unit: "cup" },
      { item: "Cream cheese, softened", amount: 8, unit: "oz" },
      { item: "Ranch dressing", amount: 0.5, unit: "cup" },
      { item: "Cheddar cheese, shredded", amount: 1.5, unit: "cups" },
      { item: "Mozzarella, shredded", amount: 0.5, unit: "cup" },
      { item: "Chicken broth", amount: 0.25, unit: "cup" },
      { item: "Green onions", amount: 3, unit: "stalks" }
    ],
    steps: [
      "Preheat oven to 375°F. Cook pasta to al dente. Drain.",
      "Beat cream cheese until smooth. Mix in buffalo sauce, ranch, and chicken broth.",
      "Stir in shredded chicken and drained pasta.",
      "Pour into a greased 9×13 baking dish. Top with cheddar and mozzarella.",
      "Bake 25–30 minutes until bubbly and golden.",
      "Rest 5 minutes. Garnish with sliced green onions and a drizzle of extra buffalo sauce."
    ]
  },
  {
    id: 30,
    title: "Lemon Herb Baked Chicken",
    subtitle: "With roasted potatoes",
    category: "Chicken",
    time: 55,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍋",
    color: "#f0e890",
    ingredients: [
      { item: "Chicken breasts or thighs", amount: 4, unit: "pieces" },
      { item: "Baby potatoes, halved", amount: 1.5, unit: "lbs" },
      { item: "Lemon juice & zest", amount: 1, unit: "lemon" },
      { item: "Olive oil", amount: 3, unit: "tbsp" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Fresh rosemary", amount: 2, unit: "sprigs" },
      { item: "Fresh thyme", amount: 3, unit: "sprigs" },
      { item: "Dijon mustard", amount: 1, unit: "tbsp" },
      { item: "Salt & pepper", amount: 1, unit: "generously" }
    ],
    steps: [
      "Whisk together olive oil, lemon juice & zest, garlic, Dijon, rosemary (chopped), thyme, salt, and pepper.",
      "Toss potatoes in half the marinade. Place in a large baking dish.",
      "Coat chicken in remaining marinade. Nestle on top of potatoes.",
      "Bake at 400°F for 40–45 minutes, basting once with pan juices halfway through.",
      "Chicken is done when internal temperature reaches 165°F and potatoes are golden.",
      "Squeeze extra lemon over everything before serving."
    ]
  },
  {
    id: 31,
    title: "Crispy Parmesan Chicken Cutlets",
    subtitle: "Golden, crunchy & satisfying",
    category: "Chicken",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍗",
    color: "#e8d090",
    ingredients: [
      { item: "Chicken breasts, pounded thin", amount: 4, unit: "breasts" },
      { item: "Panko breadcrumbs", amount: 1, unit: "cup" },
      { item: "Parmesan cheese, finely grated", amount: 0.75, unit: "cup" },
      { item: "Eggs", amount: 2, unit: "large" },
      { item: "Garlic powder", amount: 1, unit: "tsp" },
      { item: "Onion powder", amount: 0.5, unit: "tsp" },
      { item: "Italian seasoning", amount: 1, unit: "tsp" },
      { item: "Olive oil", amount: 4, unit: "tbsp" },
      { item: "Lemon wedges", amount: 1, unit: "to serve" }
    ],
    steps: [
      "Set up a breading station: flour in one dish, beaten eggs in another, and panko mixed with Parmesan, garlic powder, onion powder, and Italian seasoning in a third.",
      "Dip each chicken cutlet: flour → egg → panko mixture, pressing firmly.",
      "Heat olive oil in a large skillet over medium-high heat.",
      "Cook cutlets 3–4 minutes per side until deeply golden and crispy. Don't move them while they cook.",
      "Transfer to a wire rack (not paper towels) to keep the crust crispy.",
      "Serve immediately with lemon wedges. Works as a main or on sandwiches."
    ]
  },
  {
    id: 32,
    title: "One-Pot Creamy Tomato Basil Pasta",
    subtitle: "All in one pot, minimal cleanup",
    category: "Pasta",
    time: 25,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍝",
    color: "#f0b8a0",
    ingredients: [
      { item: "Spaghetti or linguine", amount: 12, unit: "oz" },
      { item: "Crushed tomatoes (canned)", amount: 1, unit: "28-oz can" },
      { item: "Heavy cream", amount: 0.5, unit: "cup" },
      { item: "Vegetable broth", amount: 2.5, unit: "cups" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Onion, sliced thin", amount: 1, unit: "medium" },
      { item: "Fresh basil", amount: 1, unit: "large handful" },
      { item: "Parmesan, for serving", amount: 1, unit: "to taste" },
      { item: "Olive oil", amount: 2, unit: "tbsp" },
      { item: "Red pepper flakes", amount: 0.5, unit: "tsp" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Add pasta, crushed tomatoes, broth, garlic, onion, olive oil, and red pepper flakes all into ONE large pot.",
      "Bring to a boil, then simmer vigorously, stirring frequently, for 9–12 minutes until pasta is al dente and sauce has thickened.",
      "Stir in heavy cream. Cook 1 more minute.",
      "Tear in fresh basil, stir through. Season generously.",
      "Serve in bowls with Parmesan. Seriously — one pot, 25 minutes."
    ]
  },
  {
    id: 33,
    title: "Baked Mac and Cheese",
    subtitle: "Stovetop to oven — ultra creamy",
    category: "Pasta",
    time: 50,
    servings: 6,
    difficulty: "Medium",
    emoji: "🧀",
    color: "#f0d060",
    ingredients: [
      { item: "Elbow macaroni", amount: 1, unit: "lb" },
      { item: "Sharp cheddar, freshly grated", amount: 3, unit: "cups" },
      { item: "Gruyère, grated", amount: 1, unit: "cup" },
      { item: "Whole milk", amount: 2, unit: "cups" },
      { item: "Heavy cream", amount: 1, unit: "cup" },
      { item: "Butter", amount: 4, unit: "tbsp" },
      { item: "All-purpose flour", amount: 3, unit: "tbsp" },
      { item: "Dijon mustard", amount: 1, unit: "tsp" },
      { item: "Smoked paprika", amount: 0.5, unit: "tsp" },
      { item: "Panko breadcrumbs", amount: 0.5, unit: "cup" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Cook pasta 2 minutes less than package says. Drain and set aside.",
      "Make béchamel: melt butter, whisk in flour, cook 1 minute. Gradually whisk in milk and cream until smooth. Simmer until thickened.",
      "Stir in Dijon, paprika, and 2/3 of the cheese until melted and silky.",
      "Fold in pasta. Season generously. Pour into a buttered baking dish.",
      "Top with remaining cheese and panko. Dot with a little butter.",
      "Bake at 375°F for 25 minutes until golden and bubbling at the edges.",
      "Rest 5 minutes before serving. The top should be crispy and the inside ultra creamy."
    ]
  },
  {
    id: 34,
    title: "Spaghetti with Meat Sauce",
    subtitle: "Easy weeknight, big flavour",
    category: "Pasta",
    time: 40,
    servings: 6,
    difficulty: "Easy",
    emoji: "🍝",
    color: "#e8a890",
    ingredients: [
      { item: "Spaghetti", amount: 1, unit: "lb" },
      { item: "Ground beef", amount: 1, unit: "lb" },
      { item: "Crushed tomatoes", amount: 1, unit: "28-oz can" },
      { item: "Tomato paste", amount: 2, unit: "tbsp" },
      { item: "Onion, diced", amount: 1, unit: "medium" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Italian seasoning", amount: 2, unit: "tsp" },
      { item: "Red wine (optional)", amount: 0.25, unit: "cup" },
      { item: "Sugar", amount: 1, unit: "pinch" },
      { item: "Olive oil", amount: 2, unit: "tbsp" },
      { item: "Parmesan, for serving", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Sauté onion and garlic in olive oil over medium heat until soft, about 5 minutes.",
      "Add ground beef. Cook until browned, breaking into small pieces. Drain fat.",
      "Stir in tomato paste; cook 1 minute until darkened.",
      "Add red wine (if using) and let it reduce 2 minutes.",
      "Add crushed tomatoes, Italian seasoning, and a pinch of sugar. Season with salt and pepper.",
      "Simmer 20–25 minutes, stirring occasionally, until sauce is rich and thick.",
      "Cook spaghetti to al dente. Drain. Toss with sauce and serve with Parmesan."
    ]
  },
  {
    id: 35,
    title: "Creamy Spinach & Mushroom Pasta",
    subtitle: "Vegetarian and deeply satisfying",
    category: "Pasta",
    time: 25,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍄",
    color: "#b8d8b0",
    ingredients: [
      { item: "Fettuccine or tagliatelle", amount: 12, unit: "oz" },
      { item: "Cremini mushrooms, sliced", amount: 2, unit: "cups" },
      { item: "Baby spinach", amount: 3, unit: "cups" },
      { item: "Heavy cream", amount: 1, unit: "cup" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Parmesan, grated", amount: 0.5, unit: "cup" },
      { item: "Butter", amount: 2, unit: "tbsp" },
      { item: "Olive oil", amount: 1, unit: "tbsp" },
      { item: "Fresh thyme", amount: 1, unit: "tsp" },
      { item: "Nutmeg", amount: 1, unit: "pinch" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Cook pasta to al dente. Reserve 1/2 cup pasta water before draining.",
      "Melt butter and olive oil in a large skillet over medium-high heat. Sauté mushrooms until golden, about 6 minutes — don't stir too often.",
      "Add garlic and thyme; cook 1 minute.",
      "Pour in heavy cream and add nutmeg. Simmer 3 minutes until slightly thickened.",
      "Stir in Parmesan until melted. Add spinach and let it wilt.",
      "Toss pasta in the sauce, adding pasta water to reach your preferred consistency.",
      "Season generously and serve immediately."
    ]
  },
  {
    id: 36,
    title: "Sheet Pan Sausage & Veggies",
    subtitle: "One pan, zero fuss",
    category: "Easy Meals",
    time: 35,
    servings: 4,
    difficulty: "Easy",
    emoji: "🥕",
    color: "#f0c890",
    ingredients: [
      { item: "Italian sausages, sliced", amount: 1, unit: "lb" },
      { item: "Bell peppers, sliced (mixed colors)", amount: 3, unit: "large" },
      { item: "Zucchini, sliced", amount: 2, unit: "medium" },
      { item: "Red onion, cut in wedges", amount: 1, unit: "large" },
      { item: "Cherry tomatoes", amount: 1, unit: "cup" },
      { item: "Olive oil", amount: 3, unit: "tbsp" },
      { item: "Italian seasoning", amount: 2, unit: "tsp" },
      { item: "Garlic powder", amount: 1, unit: "tsp" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Preheat oven to 425°F. Line a large sheet pan with foil or parchment.",
      "Spread sausage slices and all vegetables in an even layer on the pan.",
      "Drizzle olive oil over everything. Sprinkle Italian seasoning, garlic powder, salt, and pepper.",
      "Toss everything together right on the pan.",
      "Roast for 25–30 minutes, flipping halfway, until sausages are caramelized and veggies are tender with charred edges.",
      "Serve as-is or over rice, pasta, or with crusty bread."
    ]
  },
  {
    id: 37,
    title: "Ground Turkey Taco Skillet",
    subtitle: "Lighter and just as tasty",
    category: "Easy Meals",
    time: 25,
    servings: 4,
    difficulty: "Easy",
    emoji: "🌮",
    color: "#e8d0a0",
    ingredients: [
      { item: "Ground turkey", amount: 1.5, unit: "lbs" },
      { item: "Black beans (canned, drained)", amount: 1, unit: "15-oz can" },
      { item: "Corn (canned or frozen)", amount: 1, unit: "cup" },
      { item: "Diced tomatoes (canned)", amount: 1, unit: "14-oz can" },
      { item: "Taco seasoning", amount: 1, unit: "packet" },
      { item: "Onion, diced", amount: 1, unit: "medium" },
      { item: "Garlic cloves, minced", amount: 3, unit: "cloves" },
      { item: "Cheddar cheese, shredded", amount: 1, unit: "cup" },
      { item: "Sour cream", amount: 1, unit: "to serve" },
      { item: "Tortilla chips", amount: 1, unit: "to serve" }
    ],
    steps: [
      "Brown ground turkey in a large skillet. Drain any liquid.",
      "Add onion and garlic, cook 3 minutes.",
      "Stir in taco seasoning, black beans, corn, and diced tomatoes (with liquid).",
      "Simmer 8–10 minutes until slightly thickened.",
      "Top with shredded cheddar and cover for 2 minutes to melt.",
      "Serve with tortilla chips, sour cream, and any toppings you like."
    ]
  },
  {
    id: 38,
    title: "Skillet Lasagna",
    subtitle: "No-bake, ready in 30 minutes",
    category: "Easy Meals",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍳",
    color: "#e8a090",
    ingredients: [
      { item: "Ground beef or Italian sausage", amount: 1, unit: "lb" },
      { item: "Lasagna noodles, broken into pieces", amount: 8, unit: "noodles" },
      { item: "Crushed tomatoes", amount: 1, unit: "28-oz can" },
      { item: "Ricotta cheese", amount: 1, unit: "cup" },
      { item: "Mozzarella, shredded", amount: 1.5, unit: "cups" },
      { item: "Garlic cloves, minced", amount: 3, unit: "cloves" },
      { item: "Italian seasoning", amount: 2, unit: "tsp" },
      { item: "Water", amount: 0.5, unit: "cup" },
      { item: "Parmesan", amount: 0.25, unit: "cup" }
    ],
    steps: [
      "Brown meat in a large, deep skillet. Drain fat. Add garlic, cook 1 minute.",
      "Add Italian seasoning and crushed tomatoes. Season with salt and pepper.",
      "Nestle broken lasagna noodle pieces into the sauce. Add water.",
      "Cover and simmer 15–18 minutes, stirring occasionally, until pasta is tender.",
      "Drop spoonfuls of ricotta over the top. Sprinkle mozzarella and Parmesan.",
      "Cover 2 minutes to melt cheese. Serve right from the skillet."
    ]
  },
  {
    id: 39,
    title: "One-Pan Salmon with Asparagus",
    subtitle: "Elegant and ready in 20 minutes",
    category: "Seafood",
    time: 20,
    servings: 2,
    difficulty: "Easy",
    emoji: "🐟",
    color: "#c8d8c8",
    ingredients: [
      { item: "Salmon fillets", amount: 2, unit: "fillets" },
      { item: "Asparagus, trimmed", amount: 1, unit: "bunch" },
      { item: "Butter", amount: 2, unit: "tbsp" },
      { item: "Garlic cloves, minced", amount: 3, unit: "cloves" },
      { item: "Lemon, sliced", amount: 1, unit: "lemon" },
      { item: "Fresh dill", amount: 2, unit: "tbsp" },
      { item: "Olive oil", amount: 2, unit: "tbsp" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Preheat oven to 400°F. Line a sheet pan with foil.",
      "Toss asparagus with olive oil, salt, and pepper. Spread on one side of the pan.",
      "Season salmon fillets and place on the other side. Top each with lemon slices.",
      "Melt butter with garlic. Drizzle over both salmon and asparagus.",
      "Bake 12–15 minutes until salmon flakes easily and asparagus is tender.",
      "Scatter fresh dill over everything and serve with extra lemon."
    ]
  },
  {
    id: 40,
    title: "Beef & Broccoli Stir Fry",
    subtitle: "Better than takeout — 30 minutes",
    category: "Beef",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    emoji: "🥩",
    color: "#c8d8b8",
    ingredients: [
      { item: "Flank steak or sirloin, thinly sliced", amount: 1.5, unit: "lbs" },
      { item: "Broccoli florets", amount: 3, unit: "cups" },
      { item: "Soy sauce", amount: 4, unit: "tbsp" },
      { item: "Oyster sauce", amount: 2, unit: "tbsp" },
      { item: "Sesame oil", amount: 1, unit: "tbsp" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Fresh ginger, grated", amount: 1, unit: "tsp" },
      { item: "Brown sugar", amount: 1, unit: "tbsp" },
      { item: "Cornstarch", amount: 2, unit: "tsp" },
      { item: "Vegetable oil", amount: 2, unit: "tbsp" },
      { item: "Sesame seeds & rice (to serve)", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Mix soy sauce, oyster sauce, sesame oil, brown sugar, garlic, ginger, and cornstarch into a marinade.",
      "Toss sliced beef in half the sauce. Marinate 10 minutes.",
      "Blanch broccoli in boiling salted water for 2 minutes. Drain.",
      "Heat vegetable oil in a wok over high heat until smoking. Stir-fry beef in batches until caramelized, 2–3 minutes. Remove.",
      "Add broccoli to the wok, stir-fry 2 minutes. Add remaining sauce.",
      "Return beef to the wok. Toss everything together for 1 minute.",
      "Serve over rice, scattered with sesame seeds."
    ]
  },
  {
    id: 41,
    title: "White Chicken Chili",
    subtitle: "Creamy, hearty & warming",
    category: "Soups & Bakes",
    time: 40,
    servings: 6,
    difficulty: "Easy",
    emoji: "🥣",
    color: "#e8d8c0",
    ingredients: [
      { item: "Chicken breasts, cooked & shredded", amount: 3, unit: "cups" },
      { item: "White beans (canned, drained)", amount: 2, unit: "15-oz cans" },
      { item: "Chicken broth", amount: 4, unit: "cups" },
      { item: "Green chiles (canned)", amount: 2, unit: "4-oz cans" },
      { item: "Cream cheese", amount: 4, unit: "oz" },
      { item: "Heavy cream", amount: 0.5, unit: "cup" },
      { item: "Onion, diced", amount: 1, unit: "medium" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Cumin", amount: 1.5, unit: "tsp" },
      { item: "Chili powder", amount: 1, unit: "tsp" },
      { item: "Lime juice", amount: 2, unit: "tbsp" }
    ],
    steps: [
      "Sauté onion and garlic in a large pot over medium heat until softened, about 4 minutes.",
      "Add green chiles, cumin, and chili powder. Stir and cook 1 minute.",
      "Add chicken broth and white beans. Bring to a simmer, 10 minutes.",
      "Mash about 1/3 of the beans against the pot side to thicken the chili.",
      "Stir in cream cheese and heavy cream until smooth.",
      "Add shredded chicken and lime juice. Simmer 5 more minutes.",
      "Serve topped with sour cream, tortilla strips, shredded cheese, and cilantro."
    ]
  },
  {
    id: 42,
    title: "Loaded Baked Potato Soup",
    subtitle: "All the toppings, none of the waiting",
    category: "Soups & Bakes",
    time: 45,
    servings: 6,
    difficulty: "Medium",
    emoji: "🥔",
    color: "#e0c898",
    ingredients: [
      { item: "Russet potatoes, peeled & diced", amount: 2, unit: "lbs" },
      { item: "Bacon, chopped", amount: 8, unit: "strips" },
      { item: "Chicken broth", amount: 4, unit: "cups" },
      { item: "Heavy cream", amount: 1, unit: "cup" },
      { item: "Sharp cheddar, shredded", amount: 1.5, unit: "cups" },
      { item: "Sour cream", amount: 0.5, unit: "cup" },
      { item: "Onion, diced", amount: 1, unit: "medium" },
      { item: "Garlic cloves, minced", amount: 3, unit: "cloves" },
      { item: "Butter", amount: 2, unit: "tbsp" },
      { item: "Green onions (to garnish)", amount: 1, unit: "handful" }
    ],
    steps: [
      "Cook bacon in a large pot until crispy. Remove and set aside. Leave 1 tbsp drippings.",
      "Sauté onion and garlic in the drippings until soft.",
      "Add potatoes and broth. Bring to a boil and cook until potatoes are very tender, about 15 minutes.",
      "Mash some of the potatoes with the back of a spoon to your desired thickness.",
      "Stir in cream, sour cream, and cheddar until smooth and melty.",
      "Season well. Ladle into bowls and top with bacon, more cheddar, and green onions."
    ]
  },
  {
    id: 43,
    title: "Cheesy Beef & Rice Stuffed Peppers",
    subtitle: "Classic comfort, elevated",
    category: "Soups & Bakes",
    time: 55,
    servings: 4,
    difficulty: "Medium",
    emoji: "🫑",
    color: "#b8d8a8",
    ingredients: [
      { item: "Large bell peppers (any color)", amount: 4, unit: "large" },
      { item: "Ground beef", amount: 1, unit: "lb" },
      { item: "Cooked white rice", amount: 1.5, unit: "cups" },
      { item: "Tomato sauce", amount: 1, unit: "15-oz can" },
      { item: "Cheddar cheese, shredded", amount: 1.5, unit: "cups" },
      { item: "Onion, diced", amount: 0.5, unit: "medium" },
      { item: "Garlic cloves, minced", amount: 2, unit: "cloves" },
      { item: "Italian seasoning", amount: 1, unit: "tsp" },
      { item: "Worcestershire sauce", amount: 1, unit: "tbsp" },
      { item: "Salt & pepper", amount: 1, unit: "to taste" }
    ],
    steps: [
      "Preheat oven to 375°F. Cut tops off peppers, remove seeds. Blanch in boiling water 5 minutes.",
      "Brown ground beef with onion and garlic. Drain fat.",
      "Stir in Italian seasoning, Worcestershire, salt, and pepper.",
      "Mix in tomato sauce, rice, and 1 cup of cheese.",
      "Fill each pepper generously with the beef mixture. Stand them in a baking dish.",
      "Top with remaining cheese. Add 1/4 cup water to the bottom of the dish.",
      "Cover with foil and bake 30 minutes. Uncover and bake 10 more minutes until cheese is golden."
    ]
  },
  {
    id: 44,
    title: "Chicken Enchilada Casserole",
    subtitle: "All the flavour, none of the rolling",
    category: "Soups & Bakes",
    time: 50,
    servings: 6,
    difficulty: "Easy",
    emoji: "🌯",
    color: "#f0c090",
    ingredients: [
      { item: "Cooked chicken, shredded", amount: 3, unit: "cups" },
      { item: "Corn tortillas, torn in pieces", amount: 12, unit: "tortillas" },
      { item: "Red enchilada sauce", amount: 2, unit: "10-oz cans" },
      { item: "Mexican cheese blend, shredded", amount: 2, unit: "cups" },
      { item: "Black beans (canned, drained)", amount: 1, unit: "15-oz can" },
      { item: "Corn (frozen or canned)", amount: 1, unit: "cup" },
      { item: "Sour cream", amount: 0.5, unit: "cup" },
      { item: "Green onions", amount: 3, unit: "stalks" },
      { item: "Cumin", amount: 1, unit: "tsp" }
    ],
    steps: [
      "Preheat oven to 375°F. Grease a 9×13-inch baking dish.",
      "Spread 1/2 cup of enchilada sauce on the bottom.",
      "Layer: tortilla pieces → chicken → beans → corn → sauce → cheese. Repeat layers.",
      "Mix sour cream into the final layer of sauce before adding the top cheese.",
      "Cover with foil and bake 25 minutes. Uncover and bake 15 more minutes until bubbly.",
      "Let rest 10 minutes. Top with green onions and a drizzle of sour cream."
    ]
  },
  {
    id: 45,
    title: "Sloppy Joe Sliders",
    subtitle: "Homemade & crowd-pleasing",
    category: "Beef",
    time: 30,
    servings: 6,
    difficulty: "Easy",
    emoji: "🍔",
    color: "#f0b898",
    ingredients: [
      { item: "Ground beef", amount: 1.5, unit: "lbs" },
      { item: "Slider buns (12-pack)", amount: 1, unit: "pack" },
      { item: "Ketchup", amount: 0.5, unit: "cup" },
      { item: "Tomato paste", amount: 2, unit: "tbsp" },
      { item: "Brown sugar", amount: 1, unit: "tbsp" },
      { item: "Worcestershire sauce", amount: 1, unit: "tbsp" },
      { item: "Apple cider vinegar", amount: 1, unit: "tbsp" },
      { item: "Yellow mustard", amount: 1, unit: "tsp" },
      { item: "Onion, diced", amount: 1, unit: "medium" },
      { item: "Green pepper, diced", amount: 0.5, unit: "medium" },
      { item: "Garlic cloves, minced", amount: 2, unit: "cloves" },
      { item: "American cheese", amount: 6, unit: "slices" }
    ],
    steps: [
      "Brown ground beef in a skillet. Drain fat. Add onion, pepper, and garlic; cook 4 minutes.",
      "Stir in ketchup, tomato paste, brown sugar, Worcestershire, vinegar, and mustard.",
      "Simmer 10 minutes until sauce is thick and glossy. Season with salt and pepper.",
      "Preheat oven to 350°F. Separate slider buns, place bottoms in a baking dish.",
      "Spoon sloppy joe mixture onto buns. Add cheese slice over each.",
      "Place tops on. Brush with melted butter. Bake 10 minutes until tops are golden.",
      "Pull apart and serve hot. Messy, saucy, and absolutely delicious."
    ]
  },
  {
    id: 46,
    title: "Sun-Dried Tomato Chicken Pasta",
    subtitle: "Bold Mediterranean flavours",
    category: "Pasta",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍝",
    color: "#f0a880",
    ingredients: [
      { item: "Pasta (any shape)", amount: 12, unit: "oz" },
      { item: "Chicken breasts, diced", amount: 1.5, unit: "lbs" },
      { item: "Sun-dried tomatoes in oil, chopped", amount: 0.5, unit: "cup" },
      { item: "Heavy cream", amount: 1, unit: "cup" },
      { item: "Parmesan, grated", amount: 0.5, unit: "cup" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Baby spinach", amount: 2, unit: "cups" },
      { item: "Chicken broth", amount: 0.5, unit: "cup" },
      { item: "Italian seasoning", amount: 1, unit: "tsp" },
      { item: "Olive oil from sun-dried tomato jar", amount: 2, unit: "tbsp" }
    ],
    steps: [
      "Cook pasta to al dente. Reserve pasta water. Drain.",
      "Use the sun-dried tomato oil to sear diced chicken until golden, 5–6 minutes. Set aside.",
      "Sauté garlic and sun-dried tomatoes in the same pan for 1 minute.",
      "Add chicken broth and cream, bring to a simmer. Cook 3 minutes.",
      "Stir in Parmesan until smooth. Add spinach and wilt.",
      "Return chicken and pasta to the pan. Toss well, adding pasta water to adjust consistency.",
      "Season with Italian seasoning, salt, and pepper. Serve immediately."
    ]
  },
  {
    id: 47,
    title: "In-N-Out Style Smash Burgers",
    subtitle: "Homemade animal-style inspired",
    category: "Beef",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍔",
    color: "#f0d090",
    ingredients: [
      { item: "80/20 ground beef", amount: 1.5, unit: "lbs" },
      { item: "American cheese slices", amount: 8, unit: "slices" },
      { item: "Brioche buns", amount: 4, unit: "buns" },
      { item: "Iceberg lettuce", amount: 1, unit: "cup" },
      { item: "Tomato, sliced", amount: 2, unit: "medium" },
      { item: "Yellow onion, grilled", amount: 1, unit: "large" },
      { item: "Pickles", amount: 1, unit: "handful" },
      { item: "Mayonnaise", amount: 0.25, unit: "cup" },
      { item: "Ketchup", amount: 2, unit: "tbsp" },
      { item: "Yellow mustard", amount: 1, unit: "tbsp" },
      { item: "Sweet pickle relish", amount: 1, unit: "tbsp" },
      { item: "White vinegar", amount: 0.5, unit: "tsp" }
    ],
    steps: [
      "Make the special sauce: mix mayo, ketchup, mustard, relish, and vinegar. Set aside.",
      "Slowly caramelize sliced onions in butter over low heat for 20 minutes until golden.",
      "Divide beef into 3-oz balls. Season with salt.",
      "Heat a cast-iron skillet until smoking. Smash burgers flat immediately upon contact.",
      "Cook 2–3 minutes until deeply browned. Flip, add two slices of cheese, cover and steam 30 seconds.",
      "Build: toasted bun → special sauce → lettuce → tomato → double patty → grilled onions → pickles → more sauce.",
      "Serve immediately while hot and melty."
    ]
  },
  {
    id: 48,
    title: "Sweet Potato Pizza Bites",
    subtitle: "Pepperoni on crispy sweet potato rounds",
    category: "Sweet Potato",
    time: 30,
    servings: 3,
    difficulty: "Easy",
    emoji: "🍕",
    color: "#f5c070",
    ingredients: [
      { item: "Sweet potato, sliced into rounds", amount: 2, unit: "medium" },
      { item: "Pizza sauce", amount: 0.5, unit: "cup" },
      { item: "Mini pepperoni", amount: 1, unit: "cup" },
      { item: "Mozzarella, shredded", amount: 1, unit: "cup" },
      { item: "Olive oil", amount: 1, unit: "tbsp" },
      { item: "Italian seasoning", amount: 0.5, unit: "tsp" },
      { item: "Fresh basil (optional)", amount: 1, unit: "handful" }
    ],
    steps: [
      "Slice sweet potatoes into 1/3-inch rounds. Brush with olive oil on both sides.",
      "Roast at 400°F on a baking sheet for 20 minutes, flipping halfway.",
      "Top each round with a spoonful of pizza sauce, a pinch of mozzarella, and mini pepperoni.",
      "Bake another 8–10 minutes until cheese is melted and bubbly.",
      "Finish with fresh basil and a crack of black pepper. Serve as a snack or side."
    ]
  },
  {
    id: 49,
    title: "Mini Pepperoni Pizza Rolls",
    subtitle: "Pull-apart, cheesy & irresistible",
    category: "Pizza & Flatbreads",
    time: 35,
    servings: 6,
    difficulty: "Easy",
    emoji: "🍕",
    color: "#f0c0a0",
    ingredients: [
      { item: "Pizza dough", amount: 1, unit: "ball" },
      { item: "Pepperoni slices", amount: 30, unit: "slices" },
      { item: "Mozzarella, shredded", amount: 1.5, unit: "cups" },
      { item: "Pizza sauce (for dipping)", amount: 1, unit: "cup" },
      { item: "Garlic butter", amount: 3, unit: "tbsp" },
      { item: "Italian seasoning", amount: 1, unit: "tsp" },
      { item: "Parmesan, grated", amount: 0.25, unit: "cup" }
    ],
    steps: [
      "Preheat oven to 400°F. Roll dough out thin on a floured surface.",
      "Spread a light layer of pizza sauce over the dough. Top evenly with mozzarella and pepperoni.",
      "Roll the dough tightly into a log. Cut into 1.5-inch rounds.",
      "Place cut-side up in a greased round baking pan or cast-iron skillet, close together.",
      "Brush generously with garlic butter. Sprinkle Italian seasoning and Parmesan.",
      "Bake 20–25 minutes until golden and the cheese is bubbling.",
      "Serve warm with extra marinara for dipping. Pull-apart style!"
    ]
  },
  {
    id: 50,
    title: "Creamy Spinach & Mushroom Pasta (Upgraded)",
    subtitle: "With crispy shallots on top",
    category: "Pasta",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    emoji: "🍄",
    color: "#b8d8a8",
    ingredients: [
      { item: "Pappardelle or wide pasta", amount: 12, unit: "oz" },
      { item: "Mixed mushrooms (cremini & shiitake)", amount: 2.5, unit: "cups" },
      { item: "Baby spinach", amount: 4, unit: "cups" },
      { item: "Shallots, 2 thinly sliced for frying", amount: 3, unit: "total" },
      { item: "Heavy cream", amount: 1.25, unit: "cups" },
      { item: "Garlic cloves, minced", amount: 4, unit: "cloves" },
      { item: "Parmesan, grated", amount: 0.75, unit: "cup" },
      { item: "Butter", amount: 3, unit: "tbsp" },
      { item: "Olive oil", amount: 2, unit: "tbsp" },
      { item: "Fresh thyme", amount: 1, unit: "tbsp" },
      { item: "Truffle oil (optional)", amount: 1, unit: "drizzle" }
    ],
    steps: [
      "Fry thinly sliced shallots in 1/4-inch of hot oil until golden and crispy. Drain on paper towels, salt immediately.",
      "Cook pasta to al dente. Reserve 3/4 cup pasta water.",
      "Sauté mixed mushrooms in butter + olive oil over high heat without stirring, 5–6 minutes, until deeply golden.",
      "Add garlic, diced shallots, and thyme. Cook 1 minute.",
      "Pour in cream. Simmer 3 minutes. Stir in Parmesan.",
      "Add spinach and wilt. Toss pasta through the sauce with pasta water as needed.",
      "Plate and top with a nest of crispy shallots and a drizzle of truffle oil if using."
    ]
  }
];

// Categories
const CATEGORIES = [
  { id: "all", label: "All Recipes", icon: "✦" },
  { id: "Chicken", label: "Chicken", icon: "🍗" },
  { id: "Beef", label: "Beef", icon: "🥩" },
  { id: "Pasta", label: "Pasta", icon: "🍝" },
  { id: "Seafood", label: "Seafood", icon: "🐟" },
  { id: "Sweet Potato", label: "Sweet Potato", icon: "🍠" },
  { id: "Pizza & Flatbreads", label: "Pizza & Flatbreads", icon: "🍕" },
  { id: "Skillet Dinners", label: "Skillet Dinners", icon: "🍳" },
  { id: "Breakfast & Brunch", label: "Breakfast", icon: "🌅" },
  { id: "Drinks & Coffee", label: "Drinks", icon: "☕" },
  { id: "Easy Meals", label: "Easy Meals", icon: "⚡" },
  { id: "Soups & Bakes", label: "Soups & Bakes", icon: "🥣" },
];
